# Basic Information 
title: Tarun Suresh
position: Computer Science
affiliation: University of Illinois Urbana-Champaign
email: tsuresh3 (at) illinois.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: tarun suresh
description: academic personal homepage for tarun suresh.
canonical: https://tarun-suresh.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=Yxx6B5YAAAAJ&hl=en
linkedin: https://linkedin.com/in/tarsur909
github_link: https://github.com/tarsur909
twitter: https://twitter.com/TarunSures41845

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar_tarun.JPG
favicon: ./assets/img/favicon-32x32.png
favicon_dark: ./assets/img/favicon-32x32.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"


# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
